### ISSUE TITLE
Refactor Edit Entry

### ISSUE THREAD

**Issue by rafaehlers** [gravityview/GravityView#575]
- [x] Support Post Content field with rich text editing
- [x] Support Post Tags field
- [x] Support Post Category field
- [x] Support Post Image ( see #631  )
- [x] Support calculation fields when they are not configured to be editable in the frontend (see #626  )
- [x] Support Post Templates (see #583  )
- [ ] Remove `switch()` statements and refactor to `GravityView_Field` field classes
- [ ] Remove `$_GET['page']` hacks (use new Gravity Forms filters `gform_is_form_editor`, `gform_is_entry_detail`, `gform_is_entry_detail_edit` instead - see `GFCommon::is_form_editor()` )

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995633027696845)

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/136448301/4062/?folderId=408730

**Comment by zackkatz** [comment]
This ticket is vague and not able to be scoped. We should address in more detail later.
